version: "3.8"

services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: product_watchlist_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d product_watchlist_test"]
      interval: 5s
      timeout: 5s
      retries: 5
